wandb_version: 1

algorithm:
  desc: null
  value: sac-default-False-independent_sac
p_hidden_dimension:
  desc: null
  value:
  - 256
  - 512
q_hidden_dimension:
  desc: null
  value:
  - 256
  - 512
discount:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
alpha:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 0.0003
batch_size:
  desc: null
  value: 256
replay_buffer_capacity:
  desc: null
  value: 100000.0
standardize_start_time_step:
  desc: null
  value: null
end_exploration_time_step:
  desc: null
  value: null
action_scaling_coefficient:
  desc: null
  value: 0.5
reward_scaling:
  desc: null
  value: 5.0
update_per_time_step:
  desc: null
  value: 2
policy_type:
  desc: null
  value: default
use_target:
  desc: null
  value: false
tgelu_tr:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699866802.71632
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
