wandb_version: 1

algorithm:
  desc: null
  value: sac
learning_rate:
  desc: null
  value: 0.0003
buffer_size:
  desc: null
  value: 1000000
learning_starts:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
train_freq:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value:
    net_arch:
      pi:
      - 128
      - 256
      qf:
      - 128
      - 256
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697397365.62544
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.10.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
